apiVersion: v1
kind: ConfigMap
metadata:
  name: settle-config
  namespace: settle
data:
  REDIS_URL: redis://redis:6379/0
  BANK_URL: http://mockbank:8080
---
apiVersion: v1
kind: Secret
metadata:
  name: settle-secrets
  namespace: settle
type: Opaque
data:
  # settle:S3ttle-prod-2026
  DATABASE_URL: cG9zdGdyZXNxbCtwc3ljb3BnOi8vc2V0dGxlOlMzdHRsZS1wcm9kLTIwMjZAcG9zdGdyZXM6NTQzMi9zZXR0bGU=
