upstream settle_api {
    server settle-api.settle.svc.cluster.local:80;
}
server {
    listen 80;
    access_log /var/log/nginx/settle_access.log;
    location / {
        proxy_pass http://settle_api;
        proxy_read_timeout 5s;
        proxy_next_upstream error timeout http_502 http_504 non_idempotent;
        proxy_next_upstream_tries 3;
    }
}
